### ISSUE TITLE
BTdig site down since 3 days

### ISSUE THREAD

**Issue by DarthAdriano** [btdig/dhtcrawler2#14]
Site won't even load and stuck on a loading spinner page. This extended downtime is not common imo.

**Comment by anticpc** [comment]
![image](https://github.com/btdig/dhtcrawler2/assets/32192140/80587d10-f468-44d9-916a-701e05dc8118)

**Comment by d3wF1nk** [comment]
![image](https://github.com/btdig/dhtcrawler2/assets/26278869/0c5c5807-a639-4361-bfbf-3079eaa735b5)

**Comment by ghost** [comment]
working fine for me....

**Comment by d3w201** [comment]
now it works! thanks guys

**Comment by d3w201** [comment]
> Site won't even load and stuck on a loading spinner page. This extended downtime is not common imo.

the issue can be close 🚨
